version: 1.0.0
commands:
    magento:download:
        name: Magento Downloader
        code: magento:download
        aliases:
            - download
            - d
        description: "Downloads the Magento Open Source version"
        class: \MageLab\Command\Magento\MagentoDownloadCommand
        config:

    magento:versions:
        name: Magento Versions
        code: magento:versions
        aliases:
            - versions
        description: List all the available versions for download with MageLab tool
        class: \MageLab\Command\Magento\MagentoVersionsListCommand

    environment:download:
        name: Clone Docker Environment
        code: environment:clone
        aliases:
            - clone
        description: Download the Dockerlab docker project to a given directory
        class: \MageLab\Command\Environment\DownloadCommand

    environment:up:
        name: Get the Environment Up
        code: environment:start
        aliases:
            - start
            - up
        description: Run the docker-composer command to get the environment up and running
        class: \MageLab\Command\Environment\StartCommand

    environment:down:
        name: Get the Environment Down
        code: environment:down
        aliases:
            - down
        description: Run the docker-composer command to get the environment down
        class: \MageLab\Command\Environment\DownCommand

    environment:logs:
        name: Get the Environment Logs
        code: environment:logs
        aliases:
            - logs
            - log
        description: Get the environment logs
        class: \MageLab\Command\Environment\LogsCommand

    environment:file:create:
        name: Create the .env file
        code: environment:file:create
        aliases:
            - env-create
        description: Create the .env file with the information of the environment.
        class: \MageLab\Command\Environment\EnvFileCreateCommand

    docker_compose:
        name: Docker Compose Command
        code: docker-compose
        aliases:
            - dc
        description: Docker Compose Command
        class: \MageLab\Command\DockerComposeCommand
