version: 1.0.0
commands:
    magento_download:
        name: Magento Downloader
        code: magento:download
        aliases:
            - download
            - d
        description: "Downloads the Magento Open Source version"
        class: \MageLab\Command\Magento\MagentoDownloadCommand
        config:
    magento_versions:
        name: Magento Versions
        code: magento:versions
        aliases:
            - versions
        description: List all the available versions for download with MageLab tool
        class: \MageLab\Command\Magento\MagentoVersionsListCommand
    environment_download:
        name: Clone Docker Environment
        code: environment:clone
        aliases:
            - clone
        description: Download the Dockerlab docker project to a given directory
        class: \MageLab\Command\Environment\DownloadCommand
    environment_up:
        name: Get the Environment Up
        code: environment:start
        aliases:
            - start
            - up
        description: Run the docker-composer command to get the environment up and running
        class: \MageLab\Command\Environment\StartCommand
    environment_file_create:
        name: Create the .env file
        code: environment:file:create
        aliases:
            - env-create
        description: Create the .env file with the information of the environment.
        class: \MageLab\Command\Environment\EnvFileCreateCommand
