commands:
    magento:download:
        name: Magento Downloader
        code: magento:download
        aliases:
            - download
            - d
        description: "Downloads the Magento Open Source version"
        class: \MagedIn\Lab\Command\Magento\MagentoDownloadCommand
        config:

    magento:versions:
        name: Magento Versions
        code: magento:versions
        aliases:
            - versions
        description: List all the available versions for download with MageLab tool
        class: \MagedIn\Lab\Command\Magento\MagentoVersionsListCommand

    environment:clone:
        name: Clone Docker Environment
        code: environment:clone
        aliases:
            - clone
        description: Download the Dockerlab docker project to a given directory
        class: \MagedIn\Lab\Command\Environment\CloneCommand

    environment:up:
        name: Get the Environment Up
        code: environment:start
        aliases:
            - start
            - up
        description: Run the docker-composer command to get the environment up and running
        class: \MagedIn\Lab\Command\Environment\StartCommand

    environment:restart:
        name: Restart the service containers
        code: environment:restart
        aliases:
            - restart
        description: Restart the service containers
        class: \MagedIn\Lab\Command\Environment\RestartCommand

    environment:down:
        name: Get the docker containers down.
        code: environment:down
        aliases:
            - down
        description: Stop the docker containers and then remove them.
        class: \MagedIn\Lab\Command\Environment\DownCommand

    environment:stop:
        name: Stop the docker containers (don't remove the containers).
        code: environment:stop
        aliases:
            - stop
        description: Stop the docker containers (don't remove the containers).
        class: \MagedIn\Lab\Command\Environment\StopCommand

    environment:logs:
        name: Get the Environment Logs
        code: environment:logs
        aliases:
            - logs
            - log
        description: Get the environment logs
        class: \MagedIn\Lab\Command\Environment\LogsCommand

    environment:status:
        name: Show the containers status (same as docker-compose ps).
        code: environment:status
        aliases:
            - status
            - ps
        description: Show the containers status (same as docker-compose ps).
        class: \MagedIn\Lab\Command\Environment\StatusCommand

    environment:file:create:
        name: Create the .env file
        code: environment:file:create
        aliases:
            - env:create
        description: Create the .env file with the information of the environment.
        class: \MagedIn\Lab\Command\Environment\EnvFileCreateCommand

    environment:vhost:setup:
        name: Setup one or more vhost on Nginx
        code: environment:vhost:setup
        aliases:
            - vhost:setup
        description: Setup one or more vhost on Nginx
        class: \MagedIn\Lab\Command\Environment\VhostSetupCommand

    environment:vhost:ssl-setup:
        name: Setup SSL for a vhost
        code: environment:vhost:ssl-setup
        aliases:
            - vhost:ssl:setup
            - ssl:setup
        description: Setup SSL for a vhost
        class: \MagedIn\Lab\Command\Environment\VhostSslSetupCommand

    php:xdebug:status:
        name: Show whether Xdebug is enabled or not
        code: php:xdebug:status
        aliases:
            - xdebug:status
        description: Show whether Xdebug is enabled or not
        class: \MagedIn\Lab\Command\Php\XdebugStatusCommand

    php:xdebug:toggle:
        name: Toggle Xdebug status (enabled/disabled)
        code: php:xdebug:toggle
        aliases:
            - xdebug
            - xdebug:toggle
        description: Toggle Xdebug status (enabled/disabled)
        class: \MagedIn\Lab\Command\Php\XdebugToggleCommand

    php:xdebug:enabled:
        name: Enable Xdebug
        code: php:xdebug:enable
        aliases:
            - xdebug:enable
        description: Enable Xdebug
        class: \MagedIn\Lab\Command\Php\XdebugEnableCommand

    php:xdebug:disable:
        name: Disable Xdebug
        code: php:xdebug:disable
        aliases:
            - xdebug:disable
        description: Disable Xdebug
        class: \MagedIn\Lab\Command\Php\XdebugDisableCommand

    php:xdebug:request-mode:
        name: Change Xdebug Request Mode
        code: php:xdebug:request-mode
        aliases:
            - xdebug:request-mode
        description: Change Xdebug Request Mode
        class: \MagedIn\Lab\Command\Php\XdebugRequestModeCommand

    php:xdebug:mode:
        name: Change Xdebug Mode
        code: php:xdebug:mode
        aliases:
            - xdebug:mode
        description: Change Xdebug Mode
        class: \MagedIn\Lab\Command\Php\XdebugModeCommand

    php:composer:
        name: Run Composer
        code: php:composer
        aliases:
            - composer
        description: Run Composer
        class: \MagedIn\Lab\Command\Php\ComposerCommand

    container:ssh:
        name: SSH into a service container
        code: container:ssh
        aliases:
            - ssh
        description: SSH into a service container
        class: \MagedIn\Lab\Command\Container\SshCommand

    magento:cli:
        name: Magento 2 CLI
        code: magento:cli
        aliases:
            - m
            - magento
            - mage
        description: Magento 2 CLI
        class: \MagedIn\Lab\Command\Magento\MagentoCommand

    n98:
        name: n98 Magerun Script
        code: n98
        aliases:
            - magerun
        description: n98 Magerun Script
        class: \MagedIn\Lab\Command\Magento\N98Command

    mkcert:ssl:generate:
        name: Generate self-signed SSL files for local development
        code: mkcert:ssl:generate
        aliases:
            - ssl:generate
            - ssl
        description: Generate self-signed SSL files for local development
        class: \MagedIn\Lab\Command\Mkcert\MkcertSslGenerateCommand

    mkcert:install:
        name: Install the local CA in the system trust store.
        code: mkcert:install
        aliases:
        description: Install the local CA in the system trust store.
        class: \MagedIn\Lab\Command\Mkcert\MkcertInstallCommand

    mkcert:uninstall:
        name: Uninstall the local CA (but do not delete it).
        code: mkcert:uninstall
        aliases:
        description: Uninstall the local CA (but do not delete it).
        class: \MagedIn\Lab\Command\Mkcert\MkcertUninstallCommand
